name: CI

on: pull_request

jobs:
  test:
    name: Test CI

    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build tool
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Test code
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
